language: cpp
sudo: true
dist: xenial
compiler:
  - gcc
os:
  - linux
env:
  - TOOLS_DIR=$TRAVIS_BUILD_DIR/tools
script: bash ./ci.sh
cache:
  directories:
    - tools/openmpi
notification:
  email: false
